# Generated by Django 2.2 on 2020-06-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
