# Generated by Django 2.2 on 2020-06-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_auto_20200621_1938'),
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='leituras',
            field=models.ManyToManyField(blank=True, related_name='leituras', to='recurso.Recurso'),
        ),
    ]
