# Generated by Django 2.2 on 2020-06-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_auto_20200621_1938'),
        ('aula', '0002_aula_leituras'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='audios',
            field=models.ManyToManyField(blank=True, related_name='audios', to='recurso.Recurso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='demos',
            field=models.ManyToManyField(blank=True, related_name='demos', to='recurso.Recurso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='ensinos',
            field=models.ManyToManyField(blank=True, related_name='ensinos', to='recurso.Recurso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='praticas',
            field=models.ManyToManyField(blank=True, related_name='praticas', to='recurso.Recurso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='recurso.Recurso'),
        ),
    ]
