# Generated by Django 2.2 on 2020-06-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_auto_20200621_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Atalho'),
        ),
    ]
